### ISSUE TITLE
FMN does not handle redis errors

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/fmn#185]
Staging crashed with the following traceback:
```
May 01 20:34:16 notifs-backend01.stg.phx2.fedoraproject.org python2[5334]: No handlers could be found for logger "fmn.rules.utils"
May 01 20:34:16 notifs-backend01.stg.phx2.fedoraproject.org python2[5334]: WARNING:moksha.hub:Building the FAS cache into redis.
May 01 20:34:16 notifs-backend01.stg.phx2.fedoraproject.org python2[5334]: Traceback (most recent call last):
May 01 20:34:16 notifs-backend01.stg.phx2.fedoraproject.org python2[5334]: File "/usr/lib/python2.7/site-packages/fmn/consumer/backend.py", line 41, in <module>
May 01 20:34:16 notifs-backend01.stg.phx2.fedoraproject.org python2[5334]: fmn.consumer.fmn_fasshim.make_fas_cache(**CONFIG)
May 01 20:34:16 notifs-backend01.stg.phx2.fedoraproject.org python2[5334]: File "/usr/lib/python2.7/site-packages/fmn/consumer/fmn_fasshim.py", line 34, in make_fas_cache
May 01 20:34:16 notifs-backend01.stg.phx2.fedoraproject.org python2[5334]: if _cache.get('fas_cache_built'):
May 01 20:34:16 notifs-backend01.stg.phx2.fedoraproject.org python2[5334]: File "/usr/lib/python2.7/site-packages/dogpile/cache/region.py", line 454, in get
May 01 20:34:16 notifs-backend01.stg.phx2.fedoraproject.org python2[5334]: value = self.backend.get(key)
May 01 20:34:16 notifs-backend01.stg.phx2.fedoraproject.org python2[5334]: File "/usr/lib/python2.7/site-packages/dogpile/cache/backends/redis.py", line 144, in get
May 01 20:34:16 notifs-backend01.stg.phx2.fedoraproject.org python2[5334]: value = self.client.get(key)
May 01 20:34:16 notifs-backend01.stg.phx2.fedoraproject.org python2[5334]: File "/usr/lib/python2.7/site-packages/redis/client.py", line 863, in get
May 01 20:34:16 notifs-backend01.stg.phx2.fedoraproject.org python2[5334]: return self.execute_command('GET', name)
May 01 20:34:16 notifs-backend01.stg.phx2.fedoraproject.org python2[5334]: File "/usr/lib/python2.7/site-packages/redis/client.py", line 571, in execute_command
May 01 20:34:16 notifs-backend01.stg.phx2.fedoraproject.org python2[5334]: return self.parse_response(connection, command_name, **options)
May 01 20:34:16 notifs-backend01.stg.phx2.fedoraproject.org python2[5334]: File "/usr/lib/python2.7/site-packages/redis/client.py", line 577, in parse_response
May 01 20:34:16 notifs-backend01.stg.phx2.fedoraproject.org python2[5334]: response = connection.read_response()
May 01 20:34:16 notifs-backend01.stg.phx2.fedoraproject.org python2[5334]: File "/usr/lib/python2.7/site-packages/redis/connection.py", line 569, in read_response
May 01 20:34:16 notifs-backend01.stg.phx2.fedoraproject.org python2[5334]: response = self._parser.read_response()
May 01 20:34:16 notifs-backend01.stg.phx2.fedoraproject.org python2[5334]: File "/usr/lib/python2.7/site-packages/redis/connection.py", line 241, in read_response
May 01 20:34:16 notifs-backend01.stg.phx2.fedoraproject.org python2[5334]: raise error
May 01 20:34:16 notifs-backend01.stg.phx2.fedoraproject.org python2[5334]: redis.exceptions.BusyLoadingError: Redis is loading the dataset in memory
```

**Comment by jeremycline** [comment]
This shouldn't be a problem anymore now that we use Celery.
