### ISSUE TITLE
The FMN worker doesn't work if the cache backend isn't available

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/fmn#186]
FMN should not stop working if the cache its working with becomes unavailable. At the moment the worker runs into problems when redis is down:
```
May 03 16:11:00 fmn-dev.example.com python[6455]: Traceback (most recent call last):
May 03 16:11:00 fmn-dev.example.com python[6455]:   File "/home/vagrant/devel/fmn/lib/__init__.py", line 84, in matches
May 03 16:11:00 fmn-dev.example.com python[6455]:     value = fn(config, message, **arguments)
May 03 16:11:00 fmn-dev.example.com python[6455]:   File "/home/vagrant/devel/fmn/rules/generic.py", line 21, in user_filter
May 03 16:11:00 fmn-dev.example.com python[6455]:     return fasnick in fmn.rules.utils.msg2usernames(message, **config)
May 03 16:11:00 fmn-dev.example.com python[6455]:   File "/home/vagrant/devel/fmn/rules/utils.py", line 258, in msg2usernames
May 03 16:11:00 fmn-dev.example.com python[6455]:     return _cache.get_or_create(key, creator)
May 03 16:11:00 fmn-dev.example.com python[6455]:   File "/home/vagrant/.virtualenvs/fmn/lib/python2.7/site-packages/dogpile/cache/region.py", line 825, in get_or_create
May 03 16:11:00 fmn-dev.example.com python[6455]:     async_creator) as value:
May 03 16:11:00 fmn-dev.example.com python[6455]:   File "/home/vagrant/.virtualenvs/fmn/lib/python2.7/site-packages/dogpile/lock.py", line 154, in __enter__
May 03 16:11:00 fmn-dev.example.com python[6455]:     return self._enter()
May 03 16:11:00 fmn-dev.example.com python[6455]:   File "/home/vagrant/.virtualenvs/fmn/lib/python2.7/site-packages/dogpile/lock.py", line 87, in _enter
May 03 16:11:00 fmn-dev.example.com python[6455]:     value = value_fn()
May 03 16:11:00 fmn-dev.example.com python[6455]:   File "/home/vagrant/.virtualenvs/fmn/lib/python2.7/site-packages/dogpile/cache/region.py", line 780, in get_value
May 03 16:11:00 fmn-dev.example.com python[6455]:     value = self.backend.get(key)
May 03 16:11:00 fmn-dev.example.com python[6455]:   File "/home/vagrant/.virtualenvs/fmn/lib/python2.7/site-packages/dogpile/cache/backends/redis.py", line 145, in get
May 03 16:11:00 fmn-dev.example.com python[6455]:     value = self.client.get(key)
May 03 16:11:00 fmn-dev.example.com python[6455]:   File "/home/vagrant/.virtualenvs/fmn/lib/python2.7/site-packages/redis/client.py", line 880, in get
May 03 16:11:00 fmn-dev.example.com python[6455]:     return self.execute_command('GET', name)
May 03 16:11:00 fmn-dev.example.com python[6455]:   File "/home/vagrant/.virtualenvs/fmn/lib/python2.7/site-packages/redis/client.py", line 578, in execute_command
May 03 16:11:00 fmn-dev.example.com python[6455]:     connection.send_command(*args)
May 03 16:11:00 fmn-dev.example.com python[6455]:   File "/home/vagrant/.virtualenvs/fmn/lib/python2.7/site-packages/redis/connection.py", line 563, in send_command
May 03 16:11:00 fmn-dev.example.com python[6455]:     self.send_packed_command(self.pack_command(*args))
May 03 16:11:00 fmn-dev.example.com python[6455]:   File "/home/vagrant/.virtualenvs/fmn/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
May 03 16:11:00 fmn-dev.example.com python[6455]:     self.connect()
May 03 16:11:00 fmn-dev.example.com python[6455]:   File "/home/vagrant/.virtualenvs/fmn/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
May 03 16:11:00 fmn-dev.example.com python[6455]:     raise ConnectionError(self._error_message(e))
May 03 16:11:00 fmn-dev.example.com python[6455]: ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
```

**Comment by jeremycline** [comment]
Solved by moving to celery, tasks will be retried
