### ISSUE TITLE
Unhandled exception from a timed out request

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/fmn#204]
There's an unhandled exception in the backend if a request times out and it appears to cause the whole backend to stop doing anything:
```
Unhandled error in Deferred:
Unhandled Error
Traceback (most recent call last):
File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 368, in callback
self._startRunCallbacks(result)
File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 464, in _startRunCallbacks
self._runCallbacks()
File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 551, in _runCallbacks
current.result = callback(current.result, *args, **kw)
File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1101, in gotResult
_inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1045, in _inlineCallbacks
result = g.send(result)
File "/usr/lib/python2.7/site-packages/fmn/consumer/backend.py", line 216, in read
backend.handle(session, recipient, raw_msg)
File "/usr/lib/python2.7/site-packages/fmn/consumer/backends/mail.py", line 160, in handle
content = fedmsg.meta.msg2long_form(msg, **self.config) or u''
File "/usr/lib/python2.7/site-packages/fedmsg/meta/__init__.py", line 142, in __wrapper
return f(msg, **config)
File "/usr/lib/python2.7/site-packages/fedmsg/meta/__init__.py", line 161, in __wrapper
return f(msg, processor=processor, **config)
File "/usr/lib/python2.7/site-packages/fedmsg/meta/__init__.py", line 247, in msg2long_form
result = processor.long_form(msg, **config)
File "/usr/lib/python2.7/site-packages/fedmsg_meta_fedora_infrastructure/scm.py", line 67, in long_form
response = requests.get(url.format(repo=repo, rev=rev))
File "/usr/lib/python2.7/site-packages/requests/api.py", line 68, in get
return request('get', url, **kwargs)
File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
response = session.request(method=method, url=url, **kwargs)
File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
resp = self.send(prep, **send_kwargs)
File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 602, in send
history = [resp for resp in gen] if allow_redirects else []
File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 195, in resolve_redirects
allow_redirects=False,
File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
r = adapter.send(request, **kwargs)
File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(110, 'Connection timed out'))
```

**Comment by jeremycline** [comment]
Related, this also caused the backend to hang

```
Jul 06 18:31:30 notifs-backend01.phx2.fedoraproject.org python2[6610]: Unhandled error in Deferred:
Jul 06 18:31:30 notifs-backend01.phx2.fedoraproject.org python2[6610]: Unhandled Error
Jul 06 18:31:30 notifs-backend01.phx2.fedoraproject.org python2[6610]: Traceback (most recent call last):
Jul 06 18:31:30 notifs-backend01.phx2.fedoraproject.org python2[6610]: File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 368, in callback
Jul 06 18:31:30 notifs-backend01.phx2.fedoraproject.org python2[6610]: self._startRunCallbacks(result)
Jul 06 18:31:30 notifs-backend01.phx2.fedoraproject.org python2[6610]: File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 464, in _startRunCallbacks
Jul 06 18:31:30 notifs-backend01.phx2.fedoraproject.org python2[6610]: self._runCallbacks()
Jul 06 18:31:30 notifs-backend01.phx2.fedoraproject.org python2[6610]: File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 551, in _runCallbacks
Jul 06 18:31:30 notifs-backend01.phx2.fedoraproject.org python2[6610]: current.result = callback(current.result, *args, **kw)
Jul 06 18:31:30 notifs-backend01.phx2.fedoraproject.org python2[6610]: File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1101, in gotResult
Jul 06 18:31:30 notifs-backend01.phx2.fedoraproject.org python2[6610]: _inlineCallbacks(r, g, deferred)
Jul 06 18:31:30 notifs-backend01.phx2.fedoraproject.org python2[6610]: --- <exception caught here> ---
Jul 06 18:31:30 notifs-backend01.phx2.fedoraproject.org python2[6610]: File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1045, in _inlineCallbacks
Jul 06 18:31:30 notifs-backend01.phx2.fedoraproject.org python2[6610]: result = g.send(result)
Jul 06 18:31:30 notifs-backend01.phx2.fedoraproject.org python2[6610]: File "/usr/lib/python2.7/site-packages/fmn/consumer/backend.py", line 216, in read
Jul 06 18:31:30 notifs-backend01.phx2.fedoraproject.org python2[6610]: backend.handle(session, recipient, raw_msg)
Jul 06 18:31:30 notifs-backend01.phx2.fedoraproject.org python2[6610]: File "/usr/lib/python2.7/site-packages/fmn/consumer/backends/irc.py", line 371, in handle
Jul 06 18:31:30 notifs-backend01.phx2.fedoraproject.org python2[6610]: message = _format_message(msg, recipient, self.config)
Jul 06 18:31:30 notifs-backend01.phx2.fedoraproject.org python2[6610]: File "/usr/lib/python2.7/site-packages/fmn/consumer/backends/irc.py", line 76, in _format_message
Jul 06 18:31:30 notifs-backend01.phx2.fedoraproject.org python2[6610]: link = fedmsg.meta.msg2link(msg, **config)
Jul 06 18:31:30 notifs-backend01.phx2.fedoraproject.org python2[6610]: File "/usr/lib/python2.7/site-packages/fedmsg/meta/__init__.py", line 142, in __wrapper
Jul 06 18:31:30 notifs-backend01.phx2.fedoraproject.org python2[6610]: return f(msg, **config)
Jul 06 18:31:30 notifs-backend01.phx2.fedoraproject.org python2[6610]: File "/usr/lib/python2.7/site-packages/fedmsg/meta/__init__.py", line 161, in __wrapper
Jul 06 18:31:30 notifs-backend01.phx2.fedoraproject.org python2[6610]: return f(msg, processor=processor, **config)
Jul 06 18:31:30 notifs-backend01.phx2.fedoraproject.org python2[6610]: File "/usr/lib/python2.7/site-packages/fedmsg/meta/__init__.py", line 264, in msg2link
Jul 06 18:31:30 notifs-backend01.phx2.fedoraproject.org python2[6610]: return processor.link(msg, **config)
Jul 06 18:31:30 notifs-backend01.phx2.fedoraproject.org python2[6610]: File "/usr/lib/python2.7/site-packages/fedmsg_meta_fedora_infrastructure/compose.py", line 127, in link
Jul 06 18:31:30 notifs-backend01.phx2.fedoraproject.org python2[6610]: int(branch)
Jul 06 18:31:30 notifs-backend01.phx2.fedoraproject.org python2[6610]: exceptions.ValueError: invalid literal for int() with base 10: 'Modular-26'
```
