### ISSUE TITLE
FMN 1.3.1-3 has web out of sync with libraries

### ISSUE THREAD

**Issue by puiterwijk** [fedora-infra/fmn#210]
```
[Sat Jul 15 11:24:11.266401 2017] [:error] [pid 30451] Traceback (most recent call last):
[Sat Jul 15 11:24:11.266406 2017] [:error] [pid 30451]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
[Sat Jul 15 11:24:11.266410 2017] [:error] [pid 30451]     response = self.full_dispatch_request()
[Sat Jul 15 11:24:11.266413 2017] [:error] [pid 30451]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
[Sat Jul 15 11:24:11.266417 2017] [:error] [pid 30451]     rv = self.handle_user_exception(e)
[Sat Jul 15 11:24:11.266420 2017] [:error] [pid 30451]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
[Sat Jul 15 11:24:11.266424 2017] [:error] [pid 30451]     reraise(exc_type, exc_value, tb)
[Sat Jul 15 11:24:11.266427 2017] [:error] [pid 30451]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
[Sat Jul 15 11:24:11.266431 2017] [:error] [pid 30451]     rv = self.dispatch_request()
[Sat Jul 15 11:24:11.266434 2017] [:error] [pid 30451]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
[Sat Jul 15 11:24:11.266456 2017] [:error] [pid 30451]     return self.view_functions[rule.endpoint](**req.view_args)
[Sat Jul 15 11:24:11.266460 2017] [:error] [pid 30451]   File "/usr/lib/python2.7/site-packages/fmn/web/app.py", line 180, in wrapper
[Sat Jul 15 11:24:11.266463 2017] [:error] [pid 30451]     result = function(*args, **kwargs)
[Sat Jul 15 11:24:11.266466 2017] [:error] [pid 30451]   File "/usr/lib/python2.7/site-packages/fmn/web/app.py", line 170, in decorated_function
[Sat Jul 15 11:24:11.266470 2017] [:error] [pid 30451]     return function(*args, **kwargs)
[Sat Jul 15 11:24:11.266473 2017] [:error] [pid 30451]   File "/usr/lib/python2.7/site-packages/fmn/web/app.py", line 607, in example_messages
[Sat Jul 15 11:24:11.266476 2017] [:error] [pid 30451]     preferences, message.__json__(), valid_paths, fedmsg_config)
[Sat Jul 15 11:24:11.266480 2017] [:error] [pid 30451]   File "/usr/lib/python2.7/site-packages/fmn/lib/__init__.py", line 49, in recipients
[Sat Jul 15 11:24:11.266483 2017] [:error] [pid 30451]     for preference in preferences.values():
[Sat Jul 15 11:24:11.266486 2017] [:error] [pid 30451] AttributeError: 'list' object has no attribute 'values'

```

**Comment by raveit65** [comment]
i am interested in progress :-)

**Comment by raveit65** [comment]
@jeremycline 
Is this fix uploaded to server?
Currently i get this error at my preferences
https://apps.fedoraproject.org/notifications/raveit65.id.fedoraproject.org/email/52729/
```
Error talking to datanommer

(ProgrammingError) column messages.username does not exist LINE 2: ...ignature, messages.category AS messages_category, messages.u... ^ 'SELECT count(*) AS count_1 \nFROM (SELECT messages.id AS messages_id, messages.msg_id AS messages_msg_id, messages.i AS messages_i, messages.topic AS messages_topic, messages.timestamp AS messages_timestamp, messages.certificate AS messages_certificate, messages.signature AS messages_signature, messages.category AS messages_category, messages.username AS messages_username, messages.crypto AS messages_crypto, messages.source_name AS messages_source_name, messages.source_version AS messages_source_version, messages._msg AS messages__msg, messages._headers AS messages__headers \nFROM messages \nWHERE messages.timestamp BETWEEN %(timestamp_1)s AND %(timestamp_2)s AND (EXISTS (SELECT 1 \nFROM package_messages, package \nWHERE messages.id = package_messages.msg AND package.name = package_messages.package AND package.name = %(name_1)s)) AND NOT (EXISTS (SELECT 1 \nFROM user_messages, "user" \nWHERE messages.id = user_messages.msg AND "user".name = user_messages.username AND "user".name = %(name_2)s)) AND NOT ((EXISTS (SELECT 1 \nFROM package_messages, package \nWHERE messages.id = package_messages.msg AND package.name = package_messages.package AND package.name = %(name_3)s)) OR (EXISTS (SELECT 1 \nFROM package_messages, package \nWHERE messages.id = package_messages.msg AND package.name = package_messages.package AND package.name = %(name_4)s)) OR (EXISTS (SELECT 1 \nFROM package_messages, package \nWHERE messages.id = package_messages.msg AND package.name = package_messages.package AND package.name = %(name_5)s)) OR (EXISTS (SELECT 1 \nFROM package_messages, package \nWHERE messages.id = package_messages.msg AND package.name = package_messages.package AND package.name = %(name_6)s)) OR (EXISTS (SELECT 1 \nFROM package_messages, package \nWHERE messages.id = package_messages.msg AND package.name = package_messages.package AND package.name = %(name_7)s)) OR (EXISTS (SELECT 1 \nFROM package_messages, package \nWHERE messages.id = package_messages.msg AND package.name = package_messages.package AND package.name = %(name_8)s)) OR (EXISTS (SELECT 1 \nFROM package_messages, package \nWHERE messages.id = package_messages.msg AND package.name = package_messages.package AND package.name = %(name_9)s)) OR (EXISTS (SELECT 1 \nFROM package_messages, package \nWHERE messages.id = package_messages.msg AND package.name = package_messages.package AND package.name = %(name_10)s)) OR (EXISTS (SELECT 1 \nFROM package_messages, package \nWHERE messages.id = package_messages.msg AND package.name = package_messages.package AND package.name = %(name_11)s)) OR (EXISTS (SELECT 1 \nFROM package_messages, package \nWHERE messages.id = package_messages.msg AND package.name = package_messages.package AND package.name = %(name_12)s)) OR (EXISTS (SELECT 1 \nFROM package_messages, package \nWHERE messages.id = package_messages.msg AND package.name = package_messages.package AND package.name = %(name_13)s)) OR (EXISTS (SELECT 1 \nFROM package_messages, package \nWHERE messages.id = package_messages.msg AND package.name = package_messages.package AND package.name = %(name_14)s)) OR (EXISTS (SELECT 1 \nFROM package_messages, package \nWHERE messages.id = package_messages.msg AND package.name = package_messages.package AND package.name = %(name_15)s))) AND NOT (messages.category = %(category_1)s OR messages.category = %(category_2)s OR messages.category = %(category_3)s OR messages.category = %(category_4)s OR messages.category = %(category_5)s) AND NOT (messages.topic = %(topic_1)s OR messages.topic = %(topic_2)s OR messages.topic = %(topic_3)s OR messages.topic = %(topic_4)s OR messages.topic = %(topic_5)s OR messages.topic = %(topic_6)s OR messages.topic = %(topic_7)s OR messages.topic = %(topic_8)s OR messages.topic = %(topic_9)s OR messages.topic = %(topic_10)s OR messages.topic = %(topic_11)s OR messages.topic = %(topic_12)s OR messages.topic = %(topic_13)s OR messages.topic = %(topic_14)s OR messages.topic = %(topic_15)s OR messages.topic = %(topic_16)s OR messages.topic = %(topic_17)s OR messages.topic = %(topic_18)s OR messages.topic = %(topic_19)s OR messages.topic = %(topic_20)s)) AS anon_1' {'name_2': u'raveit65', 'name_3': u'cinnamon-desktop', 'topic_19': 'org.fedoraproject.prod.bodhi.update.complete.testing', 'name_1': u'rpms', 'name_6': u'cinnamon-session', 'name_7': u'lirc', 'name_4': u'cinnamon-menus', 'name_5': u'cinnamon-screensaver', 'topic_13': 'org.fedoraproject.prod.buildsys.untag', 'topic_12': 'org.fedoraproject.prod.buildsys.tag', 'topic_11': 'org.fedoraproject.prod.buildsys.rpm.sign', 'topic_10': 'org.fedoraproject.prod.copr.worker.create', 'category_3': 'anitya', 'topic_16': 'org.fedoraproject.prod.buildsys.package.list.change', 'topic_15': 'org.fedoraproject.prod.buildsys.repo.init', 'topic_14': 'org.fedoraproject.prod.buildsys.repo.done', 'topic_18': 'org.fedoraproject.prod.bodhi.update.complete.stable', 'timestamp_2': datetime.datetime(2017, 8, 15, 9, 17, 28), 'timestamp_1': datetime.datetime(2017, 6, 16, 9, 17, 28), 'category_5': 'faf', 'category_4': 'bugzilla', 'name_8': u'nemo', 'topic_17': 'org.fedoraproject.prod.bodhi.update.request.stable', 'topic_20': 'org.fedoraproject.prod.koschei.package.state.change', 'category_2': 'summershum', 'topic_7': 'org.fedoraproject.prod.mdapi.repo.update', 'topic_6': 'org.fedoraproject.prod.bodhi.masher.start', 'topic_5': 'org.fedoraproject.prod.faf.problem.threshold1', 'topic_4': 'org.fedoraproject.prod.faf.report.threshold1', 'topic_3': 'org.fedoraproject.prod.git.pkgdb2branch.complete', 'category_1': 'fedoratagger', 'topic_1': 'org.fedoraproject.prod.taskotron.result.new', 'topic_9': 'org.fedoraproject.prod.copr.chroot.start', 'topic_8': 'org.fedoraproject.prod.copr.build.start', 'name_9': u'xreader', 'name_10': u'cjs', 'name_11': u'gdk-pixbuf2', 'name_12': u'muffin', 'name_13': u'cinnamon-settings-daemon', 'name_14': u'cinnamon', 'name_15': u'xed', 'topic_2': 'org.fedoraproject.prod.git.pkgdb2branch.start'}
```
What ever that means....

**Comment by jeremycline** [comment]
It is not yet in production. No promises as to when there, but possibly next week. I'll leave a note on this ticket when I deploy it.

**Comment by jeremycline** [comment]
It should now be in production.

**Comment by raveit65** [comment]
@jeremycline 
hmm, i reset my config to factory default and i get this error message again on those filters (all).
- Events on packages that I own
- Critical taskotron tasks on my packages
- Events referring to my username

So , this issue isn't fixed.

**Comment by raveit65** [comment]
Same with adding a own filter with 2 rules.
- Messages regarding any member of a FAS group  = alt-gtk-de-sig
- All bodhi events

**Comment by raveit65** [comment]
Ok, i given up to use fedmsg for email.
I disabled it to avoid unwanted email spam from fedora for the moment.
