### ISSUE TITLE
anitya_by_upstream_project fails to check for None and raises AttributeError

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/fmn#293]
Message
-------
[2018-04-10 07:59:04][   fmn.lib   ERROR]
```python
'NoneType' object has no attribute 'get'
```

Process Details
---------------
- host:     notifs-backend01.phx2.fedoraproject.org
- PID:      17862
- name:     celery
- command:  /usr/bin/python2 /usr/bin/celery worker --pool=prefork --concurrency=1 -E -A fmn -l info -n fmn-worker1@notifs-backend01.phx2.fedoraproject.org
- msg_id:   

Callstack that lead to the logging statement
--------------------------------------------
```python
  File "/usr/bin/celery", line 11 in <module>
    load_entry_point('celery==4.0.2', 'console_scripts', 'celery')()
  File "/usr/lib/python2.7/site-packages/celery/__main__.py", line 14 in main
    _main()
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 326 in main
    cmd.execute_from_commandline(argv)
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 488 in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/lib/python2.7/site-packages/celery/bin/base.py", line 281 in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 480 in handle_argv
    return self.execute(command, argv)
  File "/usr/lib/python2.7/site-packages/celery/bin/celery.py", line 412 in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/usr/lib/python2.7/site-packages/celery/bin/worker.py", line 221 in run_from_argv
    return self(*args, **options)
  File "/usr/lib/python2.7/site-packages/celery/bin/base.py", line 244 in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/bin/worker.py", line 256 in run
    worker.start()
  File "/usr/lib/python2.7/site-packages/celery/worker/worker.py", line 203 in start
    self.blueprint.start(self)
  File "/usr/lib/python2.7/site-packages/celery/bootsteps.py", line 119 in start
    step.start(parent)
  File "/usr/lib/python2.7/site-packages/celery/bootsteps.py", line 370 in start
    return self.obj.start()
  File "/usr/lib/python2.7/site-packages/celery/concurrency/base.py", line 131 in start
    self.on_start()
  File "/usr/lib/python2.7/site-packages/celery/concurrency/prefork.py", line 112 in on_start
    **self.options)
  File "/usr/lib/python2.7/site-packages/celery/concurrency/asynpool.py", line 422 in __init__
    super(AsynPool, self).__init__(processes, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/billiard/pool.py", line 1007 in __init__
    self._create_worker_process(i)
  File "/usr/lib/python2.7/site-packages/celery/concurrency/asynpool.py", line 439 in _create_worker_process
    return super(AsynPool, self)._create_worker_process(i)
  File "/usr/lib64/python2.7/site-packages/billiard/pool.py", line 1116 in _create_worker_process
    w.start()
  File "/usr/lib64/python2.7/site-packages/billiard/process.py", line 124 in start
    self._popen = self._Popen(self)
  File "/usr/lib64/python2.7/site-packages/billiard/context.py", line 333 in _Popen
    return Popen(process_obj)
  File "/usr/lib64/python2.7/site-packages/billiard/popen_fork.py", line 24 in __init__
    self._launch(process_obj)
  File "/usr/lib64/python2.7/site-packages/billiard/popen_fork.py", line 79 in _launch
    code = process_obj._bootstrap()
  File "/usr/lib64/python2.7/site-packages/billiard/process.py", line 327 in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/site-packages/billiard/process.py", line 114 in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python2.7/site-packages/billiard/pool.py", line 289 in __call__
    sys.exit(self.workloop(pid=pid))
  File "/usr/lib64/python2.7/site-packages/billiard/pool.py", line 358 in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 530 in _fast_trace_task
    uuid, args, kwargs, request,
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 367 in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 622 in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fmn/tasks.py", line 158 in run
    self.user_preferences, message_body, self.valid_paths, config.app_conf)
  File "/usr/lib/python2.7/site-packages/fmn/lib/__init__.py", line 53 in recipients
    if matches(filter, message, valid_paths, rule_cache, config):
  File "/usr/lib/python2.7/site-packages/fmn/lib/__init__.py", line 94 in matches
    log.exception(e)
```

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/fmn/lib/__init__.py", line 86, in matches
    value = fn(config, message, **arguments)
  File "/usr/lib/python2.7/site-packages/fmn/rules/anitya.py", line 205, in anitya_by_upstream_project
    project = message.get('msg', {}).get('project', {}).get('name', None)
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by ryanlerch** [comment]
The FMN rewrite is almost complete. This issue was reported against the old version of FMN, and likely does not apply anymore.

Closing, but reopen if you feel this still applies.
