### ISSUE TITLE
Export returns 500

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/fmn#59]
I was trying to see about exporting my filter for #58 and the server returned me an error 500:

URL: https://apps.fedoraproject.org/notifications/api/pingou.id.fedoraproject.org/irc/

**Comment by ralphbean** [comment]
Here's our traceback:

``` python
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/fmn/web/app.py", line 170, in decorated_function
    return function(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fmn/web/app.py", line 433, in context_json
    return flask.jsonify(pref)
  File "/usr/lib/python2.7/site-packages/flask/json.py", line 238, in jsonify
    indent=indent),
  File "/usr/lib/python2.7/site-packages/flask/json.py", line 126, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib64/python2.7/site-packages/simplejson/__init__.py", line 369, in dumps
    **kw).encode(obj)
  File "/usr/lib64/python2.7/site-packages/simplejson/encoder.py", line 264, in encode
    chunks = list(chunks)
  File "/usr/lib64/python2.7/site-packages/simplejson/encoder.py", line 612, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/usr/lib64/python2.7/site-packages/simplejson/encoder.py", line 568, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib64/python2.7/site-packages/simplejson/encoder.py", line 455, in _iterencode_list
    for chunk in chunks:
  File "/usr/lib64/python2.7/site-packages/simplejson/encoder.py", line 568, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib64/python2.7/site-packages/simplejson/encoder.py", line 455, in _iterencode_list
    for chunk in chunks:
  File "/usr/lib64/python2.7/site-packages/simplejson/encoder.py", line 568, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib64/python2.7/site-packages/simplejson/encoder.py", line 568, in _iterencode_dict
    for chunk in chunks:
  File "/usr/lib64/python2.7/site-packages/simplejson/encoder.py", line 622, in _iterencode
    o = _default(o)
  File "/usr/lib/python2.7/site-packages/flask/json.py", line 83, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib64/python2.7/site-packages/simplejson/encoder.py", line 239, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <function _user_package_filter_hint at 0x7f9c71de29b0> is not JSON serializable
```
