### ISSUE TITLE
Getting the list of rules fails

### ISSUE THREAD

**Issue by ryanlerch** [fedora-infra/fmn#609]
After this [commit](https://github.com/fedora-infra/fmn/commit/52c0735c7910731a9b0b61ff041fc98ac0ee9dd1#diff-ae920121865ed3ec31e759f19dccc0be0d4fa70a52c5884d129ed7a3f32fbf10), getting the list of rules fails with a 500 error:

```
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]: INFO:     192.168.122.1:51792 - "GET /user/aaronhale/rules HTTP/1.1" 500 Internal Server Error
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]: ERROR:    Exception in ASGI application
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]: Traceback (most recent call last):
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]:   File "/home/vagrant/.cache/pypoetry/virtualenvs/fmn-0n_c-6Cq-py3.10/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 404>
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]:     result = await app(  # type: ignore[func-returns-value]
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]:   File "/home/vagrant/.cache/pypoetry/virtualenvs/fmn-0n_c-6Cq-py3.10/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78>
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]:     return await self.app(scope, receive, send)
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]:   File "/home/vagrant/.cache/pypoetry/virtualenvs/fmn-0n_c-6Cq-py3.10/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call>
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]:     await super().__call__(scope, receive, send)
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]:   File "/home/vagrant/.cache/pypoetry/virtualenvs/fmn-0n_c-6Cq-py3.10/lib/python3.10/site-packages/starlette/applications.py", line 124, in __ca>
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]:     await self.middleware_stack(scope, receive, send)
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]:   File "/home/vagrant/.cache/pypoetry/virtualenvs/fmn-0n_c-6Cq-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in>
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]:     raise exc
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]:   File "/home/vagrant/.cache/pypoetry/virtualenvs/fmn-0n_c-6Cq-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in>
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]:     await self.app(scope, receive, _send)
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]:   File "/home/vagrant/.cache/pypoetry/virtualenvs/fmn-0n_c-6Cq-py3.10/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __>
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]:     await self.simple_response(scope, receive, send, request_headers=headers)
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]:   File "/home/vagrant/.cache/pypoetry/virtualenvs/fmn-0n_c-6Cq-py3.10/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in s>
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]:     await self.app(scope, receive, send)
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]:   File "/home/vagrant/.cache/pypoetry/virtualenvs/fmn-0n_c-6Cq-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75,>
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]:     raise exc
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]:   File "/home/vagrant/.cache/pypoetry/virtualenvs/fmn-0n_c-6Cq-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64,>
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]:     await self.app(scope, receive, sender)
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]:   File "/home/vagrant/.cache/pypoetry/virtualenvs/fmn-0n_c-6Cq-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 2>
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]:     raise e
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]:   File "/home/vagrant/.cache/pypoetry/virtualenvs/fmn-0n_c-6Cq-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 1>
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]:     await self.app(scope, receive, send)
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]:   File "/home/vagrant/.cache/pypoetry/virtualenvs/fmn-0n_c-6Cq-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]:     await route.handle(scope, receive, send)
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]:   File "/home/vagrant/.cache/pypoetry/virtualenvs/fmn-0n_c-6Cq-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]:     await self.app(scope, receive, send)
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]:   File "/home/vagrant/.cache/pypoetry/virtualenvs/fmn-0n_c-6Cq-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]:     response = await func(request)
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]:     response = await func(request)
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]:   File "/home/vagrant/.cache/pypoetry/virtualenvs/fmn-0n_c-6Cq-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 249, in app
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]:     content = await serialize_response(
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]:   File "/home/vagrant/.cache/pypoetry/virtualenvs/fmn-0n_c-6Cq-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 138, in serialize_r>
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]:     raise ValidationError(errors, field.type_)
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]: pydantic.error_wrappers.ValidationError: 1 validation error for Rule
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]: response
Oct 12 04:39:27 fmn.tinystage.test poetry[8923]:   value is not a valid list (type=type_error.list)
```

**Comment by nphilipp** [comment]
I guess that's what we get for not testing things… 😬 i.e. solving this would partly solve #606.
