### ISSUE TITLE
Users endpoint broken

### ISSUE THREAD

**Issue by ryanlerch** [fedora-infra/fmn#656]
Somewhere around this commit: 
https://github.com/fedora-infra/fmn/commit/650b853515e1f5dffadd41a9a9373ed6fb4e50e2

the users endpoint stopped working for me. When i try to search for users, i get the error in the api logs. (note too i have done a full destroy / up of the FMN vagrant machine, so i should have all the expected deps installed)

```
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]: INFO:     192.168.122.1:43530 - "OPTIONS /api/v1/users?search=ryan HTTP/1.1" 200 OK
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]: INFO:     192.168.122.1:43530 - "GET /api/v1/users?search=ryan HTTP/1.1" 500 Internal Server Error
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]: ERROR:    Exception in ASGI application
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]: Traceback (most recent call last):
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:   File "/home/vagrant/.cache/pypoetry/virtualenvs/fmn-0n_c-6Cq-py3.10/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:     result = await app(  # type: ignore[func-returns-value]
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:   File "/home/vagrant/.cache/pypoetry/virtualenvs/fmn-0n_c-6Cq-py3.10/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:     return await self.app(scope, receive, send)
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:   File "/home/vagrant/.cache/pypoetry/virtualenvs/fmn-0n_c-6Cq-py3.10/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:     await super().__call__(scope, receive, send)
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:   File "/home/vagrant/.cache/pypoetry/virtualenvs/fmn-0n_c-6Cq-py3.10/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:     await self.middleware_stack(scope, receive, send)
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:   File "/home/vagrant/.cache/pypoetry/virtualenvs/fmn-0n_c-6Cq-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:     raise exc
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:   File "/home/vagrant/.cache/pypoetry/virtualenvs/fmn-0n_c-6Cq-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:     await self.app(scope, receive, _send)
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:   File "/home/vagrant/.cache/pypoetry/virtualenvs/fmn-0n_c-6Cq-py3.10/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:     await self.simple_response(scope, receive, send, request_headers=headers)
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:   File "/home/vagrant/.cache/pypoetry/virtualenvs/fmn-0n_c-6Cq-py3.10/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:     await self.app(scope, receive, send)
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:   File "/home/vagrant/.cache/pypoetry/virtualenvs/fmn-0n_c-6Cq-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:     raise exc
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:   File "/home/vagrant/.cache/pypoetry/virtualenvs/fmn-0n_c-6Cq-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:     await self.app(scope, receive, _send)
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:   File "/home/vagrant/.cache/pypoetry/virtualenvs/fmn-0n_c-6Cq-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:     raise exc
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:   File "/home/vagrant/.cache/pypoetry/virtualenvs/fmn-0n_c-6Cq-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:     await self.app(scope, receive, sender)
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:   File "/home/vagrant/.cache/pypoetry/virtualenvs/fmn-0n_c-6Cq-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:     raise e
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:   File "/home/vagrant/.cache/pypoetry/virtualenvs/fmn-0n_c-6Cq-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:     await self.app(scope, receive, send)
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:   File "/home/vagrant/.cache/pypoetry/virtualenvs/fmn-0n_c-6Cq-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:     await route.handle(scope, receive, send)
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:   File "/home/vagrant/.cache/pypoetry/virtualenvs/fmn-0n_c-6Cq-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:     await self.app(scope, receive, send)
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:   File "/home/vagrant/.cache/pypoetry/virtualenvs/fmn-0n_c-6Cq-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:     response = await func(request)
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:   File "/home/vagrant/.cache/pypoetry/virtualenvs/fmn-0n_c-6Cq-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 235, in app
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:     raw_response = await run_endpoint_function(
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:   File "/home/vagrant/.cache/pypoetry/virtualenvs/fmn-0n_c-6Cq-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:     return await dependant.call(**values)
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:   File "/home/vagrant/fmn/./fmn/api/handlers/users.py", line 29, in get_users
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]:     return [u["username"] async for u in fasjson_proxy.search_users(username=search)]
Nov 16 07:46:04 fmn.tinystage.test poetry[10154]: TypeError: 'async for' requires an object with __aiter__ method, got coroutine
```

**Comment by nphilipp** [comment]
That’s what we get for not testing things! 😁

**Comment by nphilipp** [comment]
PR: #658
