### ISSUE TITLE
Koji build notification fail with different errors

### ISSUE THREAD

**Issue by robert-scheck** [fedora-infra/fmn#71]
First failure:

```
sharkcz's phpMyAdmin-4.3.12-1.fc21 completed (ppc)

Package:    phpMyAdmin-4.3.12-1.fc21
Status:     complete
Built by:   sharkcz
ID:         298685
Started:    Sun, 15 Mar 2015 01:23:04 UTC
Finished:   Sun, 15 Mar 2015 01:23:04 UTC

<Fault 1: "<class 'pg.OperationalError'>: internal error in 'INIT': %d format: a number is required, not str">

        http://ppc.koji.fedoraproject.org/koji/buildinfo?buildID=298685
```

Second failure:

```
sharkcz's phpMyAdmin-4.3.12-1.fc20 completed (s390)

Package:    phpMyAdmin-4.3.12-1.fc20
Status:     complete
Built by:   sharkcz
ID:         306986
Started:    Sun, 15 Mar 2015 01:00:35 UTC
Finished:   Sun, 15 Mar 2015 01:00:35 UTC

<Fault 1: 'Traceback (most recent call last):\n  File "/usr/share/koji-hub/kojixmlrpc.py", line 212, in _wrap_handler\n    response = handler(environ)\n  File "/usr/share/koji-hub/kojixmlrpc.py", line 255, in handle_rpc\nreturn self._dispatch(method, params)\n  File "/usr/share/koji-hub/kojixmlrpc.py", line 292, in _dispatch\n    ret = koji.util.call_with_argcheck(func, params, opts)\n  File "/usr/lib/python2.6/site-packages/koji/util.py", line 139, in call_with_argcheck\n    return func(*args, **kwargs)\n  File "/usr/share/koji-hub/kojihub.py", line 8642, in getTaskInfo\n    ret = [Task(id).getInfo(False, request) for id in task_id]\n  File "/usr/share/koji-hub/kojihub.py", line 421, in getInfo\n    result = _singleRow(q, vars(self), [f[1] for f in self.fields], strict)\n  File "/usr/share/koji-hub/kojihub.py", line 3961, in _singleRow\n    row = _fetchSingle(query, values, strict)\n  File "/usr/share/koji-hub/kojihub.py", line 3933, in _fetchSingle\n    results = _fetchMulti(query, values)\n  File "/usr/share/koji-hub/kojihub.py", line 3923, in _fetchMulti\n    c.execute(query, values)\n  File "/usr/lib/python2.6/site-packages/koji/db.py", line 105, in execute\n    ret = self.cursor.execute(operation, parameters)\n  File "/usr/lib64/python2.6/site-packages/pgdb.py", line 174, in execute\n    self.executemany(operation, (params,))\n  File "/usr/lib64/python2.6/site-packages/pgdb.py", line 197, in executemany\nraise OperationalError, "internal error in \'%s\': %s" % (sql,err)\nOperationalError: internal error in \'INIT\': %d format: a number is required, not str\n'>

        http://s390.koji.fedoraproject.org/koji/buildinfo?buildID=306986
```

**Comment by ralphbean** [comment]
The original fixes for this code path that we discussed the other week just got pushed out yesterday.

Please post here if you run into them again.

**Comment by robert-scheck** [comment]
```
robert's mksh-50e-1.fc23 completed

Package:    mksh-50e-1.fc23
Status:     complete
Built by:   robert
ID:         621815
Started:    Thu, 19 Mar 2015 22:50:12 UTC
Finished:   Thu, 19 Mar 2015 22:57:01 UTC

invalid type for hostInfo: <type 'NoneType'>

        http://koji.fedoraproject.org/koji/buildinfo?buildID=621815
```
