### ISSUE TITLE
consumer pod crashing

### ISSUE THREAD

**Issue by nirik** [fedora-infra/fmn#815]
The consumer pod is currently crashing and not processing. 

It's got a traceback: 

```
[DEBUG fmn.database.model.rule] Rule 1 handling message b1181d38-8b43-41e6-97de-6e7b72108846         
[ERROR fedora_messaging.twisted.consumer] Received unexpected exception from consumer Consumer(queue=f
mn, callback=<fmn.consumer.consumer.Consumer object at 0x7f51e27cf220>)                              
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.10/site-packages/fedora_messaging/twisted/consumer.py", line 207,
in _read_one                                                                                         
    yield threads.deferToThread(self.callback, message)                                              
  File "/opt/app-root/lib64/python3.10/site-packages/twisted/python/threadpool.py", line 244, in inCon
text                                                                                                 
    result = inContext.theWork()  # type: ignore[attr-defined]                                       
  File "/opt/app-root/lib64/python3.10/site-packages/twisted/python/threadpool.py", line 260, in <lamb
da>                                                                                                  
    inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]                          
  File "/opt/app-root/lib64/python3.10/site-packages/twisted/python/context.py", line 117, in callWith
Context                                                                                              
    return self.currentContext().callWithContext(ctx, func, *args, **kw)                             
  File "/opt/app-root/lib64/python3.10/site-packages/twisted/python/context.py", line 82, in callWithC
ontext
    return func(*args, **kw)
  File "/opt/app-root/lib64/python3.10/site-packages/fmn/consumer/consumer.py", line 53, in __call__
    self.loop.run_until_complete(coro)
  File "/usr/lib64/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/app-root/lib64/python3.10/site-packages/fmn/consumer/consumer.py", line 60, in handle_or_
rollback
    await self._handle(message, db)
  File "/opt/app-root/lib64/python3.10/site-packages/fmn/consumer/consumer.py", line 77, in _handle
    db.add(Generated(rule=rule, count=1))
  File "<string>", line 4, in __init__
  File "/opt/app-root/lib64/python3.10/site-packages/sqlalchemy/orm/state.py", line 575, in _initializ
e_instance
    with util.safe_reraise():
  File "/opt/app-root/lib64/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __e
xit__
    raise exc_value.with_traceback(exc_tb)
  File "/opt/app-root/lib64/python3.10/site-packages/sqlalchemy/orm/state.py", line 573, in _initializ
e_instance
    manager.original_init(*mixed[1:], **kwargs)
  File "/opt/app-root/lib64/python3.10/site-packages/sqlalchemy/orm/decl_base.py", line 2076, in _decl
arative_constructor
    setattr(self, k, kwargs[k])
  File "/opt/app-root/lib64/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 528, in __set
__
    self.impl.set(
  File "/opt/app-root/lib64/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1453, in set
    value = self.fire_replace_event(state, dict_, value, old, initiator)
  File "/opt/app-root/lib64/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1492, in fire
_replace_event
    value = fn(
  File "/opt/app-root/lib64/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 2165, in emit
_backref_from_scalar_set_event
    child_impl.append(
  File "/opt/app-root/lib64/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1838, in appe
nd
    value = self.fire_append_event(
  File "/opt/app-root/lib64/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 1731, in fire
_append_event
    state._modified_event(dict_, self, NO_VALUE, True)
  File "/opt/app-root/lib64/python3.10/site-packages/sqlalchemy/orm/state.py", line 926, in _modified_
event
    session._autobegin_t()
  File "/opt/app-root/lib64/python3.10/site-packages/sqlalchemy/orm/session.py", line 1755, in _autobe
gin_t
    trans = SessionTransaction(
  File "/opt/app-root/lib64/python3.10/site-packages/sqlalchemy/orm/session.py", line 865, in __init__
    TransactionalContext._trans_ctx_check(session)
  File "/opt/app-root/lib64/python3.10/site-packages/sqlalchemy/engine/util.py", line 110, in _trans_c
tx_check
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Can't operate on closed transaction inside context manager.  Pleas
e complete the context manager before emitting further commands.
```

ending with sqlalchemy.exc.InvalidRequestError: Can't operate on closed transaction inside context manager.  Please complete the context manager before emitting further commands.

**Comment by abompard** [comment]
Fixed by d17f1dd9 and redeployed, the consumer is now running properly. Thanks for opening the ticket.
