### ISSUE TITLE
A rule can't be created, no error

### ISSUE THREAD

**Issue by kparal** [fedora-infra/fmn#886]
When I click _Create Rule_, nothing happens. The fields go gray for a split second and then back to editable state, no rule is created.

See here:
[fmn.webm](https://user-images.githubusercontent.com/755451/234578789-5e1f3936-b5e7-4352-ac18-27b0fbd510ec.webm)

**Comment by abompard** [comment]
Hey Kamil! I have found the traceback in the logs. Could you log out, log back in and try again please?

**Comment by abompard** [comment]
Note: the traceback is:
```
2023-04-26 12:47:49|ERROR:    Exception in ASGI application
2023-04-26 12:47:49|Traceback (most recent call last):
[...middleware...]
2023-04-26 12:47:49|  File "/opt/app-root/src/fmn/api/handlers/users.py", line 247, in create_user_rule
2023-04-26 12:47:49|    user = await User.async_get(db_session, name=username)
2023-04-26 12:47:49|  File "/opt/app-root/src/fmn/database/main.py", line 23, in async_get
2023-04-26 12:47:49|    return (await db_session.execute(select(cls).filter_by(**attrs))).scalar_one()
[...]
2023-04-26 12:47:49|sqlalchemy.exc.NoResultFound: No row was found when one was required
```

How a user can get there without being registered in the FMN DB is unknown to me (yet!). We'll have to fix that.

**Comment by abompard** [comment]
Ah, according to the logs, this may have been caused by #880.

**Comment by kparal** [comment]
Thanks, works now :-)
