### ISSUE TITLE
FMN fails to edit rule

### ISSUE THREAD

**Issue by gotmax23** [fedora-infra/fmn#922]
I'm trying to edit a rule. FMN is sending a PUT request to https://fmn-api.apps.ocp.fedoraproject.org/api/v1/users/gotmax23/rules/XX and then failing. I've attached a screenshot of the error console:

![FMN Edit Rule Failure Console](https://github.com/fedora-infra/fmn/assets/9920591/c39165d5-e171-48b7-941c-3c0023e94a15)

**Comment by abompard** [comment]
This looks like the backend tracebacking and as a result not sending the CORS headers. I'll look a the logs, thanks for the report.

**Comment by abompard** [comment]
Interesting, we're getting:

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  [...SNIP...]
asyncpg.exceptions.SerializationError: could not serialize access due to concurrent update

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  [...SNIP...]
sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.Error: <class 'asyncpg.exceptions.SerializationError'>: could not serialize access due to concurrent update

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  [...SNIP...]
  File "/opt/app-root/src/fmn/api/handlers/users.py", line 186, in edit_user_rule
    await db_session.flush()
  [...SNIP...]
sqlalchemy.exc.DBAPIError: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.SerializationError'>: could not serialize access due to concurrent update
[SQL: UPDATE rules SET name=$1::VARCHAR WHERE rules.id = $2::INTEGER]
[parameters: ('Finished Koji and Copr build (Mine)', 57)]
(Background on this error at: https://sqlalche.me/e/20/dbapi)
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  [...SNIP...]
asyncpg.exceptions.SerializationError: could not serialize access due to read/write dependencies among transactions
DETAIL:  Reason code: Canceled on identification as a pivot, during write.
HINT:  The transaction might succeed if retried.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  [...SNIP...]
sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.Error: <class 'asyncpg.exceptions.SerializationError'>: could not serialize access due to read/write dependencies among transactions
DETAIL:  Reason code: Canceled on identification as a pivot, during write.
HINT:  The transaction might succeed if retried.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  [...SNIP...]
  File "/opt/app-root/src/fmn/api/handlers/users.py", line 186, in edit_user_rule
    await db_session.flush()
  [...SNIP...]
sqlalchemy.exc.DBAPIError: (sqlalchemy.dialects.postgresql.asyncpg.Error) <class 'asyncpg.exceptions.SerializationError'>: could not serialize access due to read/write dependencies among transactions
DETAIL:  Reason code: Canceled on identification as a pivot, during write.
HINT:  The transaction might succeed if retried.
[SQL: UPDATE filters SET params=$1::JSON WHERE filters.id = $2::INTEGER]
[parameters: ('["Koji", "Copr"]', 236)]
(Background on this error at: https://sqlalche.me/e/20/dbapi)
```

(I snipped calls inside frameworks and libraries)

@nphilipp , do you want to have a look? Otherwise I can, but you know async better than I do :-)

**Comment by nphilipp** [comment]
Hm, looks like a conflict between DB transactions to me, perhaps a user was attempting to edita rule while the rule cache was being refreshed? If so, maybe we should lower the transaction isolation level for the latter as it takes some time and consistency between such transactions isn't super important.
